[package]
name = "ara"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
libc = "0.2.180"
nix = { version = "0.31.1", features = ["process", "signal", "fs"] }
rustyline = "17.0.2"
thiserror = "2.0.18"
